version: '3'
name: fiware-iotagent-json
services:
    mosquitto:
        image: eclipse-mosquitto
        hostname: mosquitto
        container_name: mosquitto
        networks:
            - default
        expose:
            - '1883'
            - '9001'
        ports:
            - '1883:1883'
            - '9001:9001'
        volumes:
            - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
networks:
  default:
    name: fiware-iotagent
    external: true
