version: "3.8"
services:
  # Orion-LD is the context broker
  orion:
    image: quay.io/fiware/orion-ld:${ORIONLD_VERSION}
    environment:
      - ORIONLD_MONGO_HOST=mongo
    hostname: orion
    container_name: fiware-orion
    depends_on:
      - mongo-db
    networks:
      - default
    expose:
      - "${ORIONLD_PORT}"
    ports:
      - "${ORIONLD_PORT}:${ORIONLD_PORT}" # localhost:1026
    command: -dbhost mongo-db -logLevel DEBUG
    healthcheck:
      test: curl --fail -s http://orion:${ORIONLD_PORT}/version || exit 1
      interval: 5s

  # Databases
  mongo-db:
    image: mongo:${MONGO_DB_VERSION}
    hostname: mongo-db
    container_name: db-mongo
    expose:
      - "${MONGO_DB_PORT}"
    ports:
      - "${MONGO_DB_PORT}:${MONGO_DB_PORT}" # localhost:27017
    networks:
      - default
    volumes:
      - mongo-db:/data
    healthcheck:
      test: [ "CMD", "mongo", "--quiet", "127.0.0.1/test", "--eval", "'quit(db.runCommand({ ping: 1 }).ok ? 0 : 2)'"]
      interval: 5s

networks:
  default:

volumes:
  mongo-db: ~
