version: "3"
name: fiware-iotagent-json
services:
  # Orion-LD is the context broker
  orion:
    image: quay.io/fiware/orion-ld:${ORIONLD_VERSION}
    environment:
      - ORIONLD_MONGO_HOST=mongo
    hostname: orion
    container_name: fiware-orion
    depends_on:
      - mongo-db
    networks:
      - default
    expose:
      - "${ORIONLD_PORT}"
    ports:
      - "${ORIONLD_PORT}:${ORIONLD_PORT}" # localhost:1026
    command: -dbhost mongo-db -logLevel DEBUG
    healthcheck:
      test: curl --fail -s http://orion:${ORIONLD_PORT}/version || exit 1
      interval: 5s
      
  iot-agent:
    image: quay.io/fiware/iotagent-json:latest
    hostname: iot-agent
    container_name: fiware-iot-agent
    depends_on:
        - mongo-db
    networks:
        - default
    expose:
        - '${IOTA_NORTH_PORT}' #port 4041
        - '${IOTA_SOUTH_PORT}' #port 7896
    ports:
        - '${IOTA_NORTH_PORT}:${IOTA_NORTH_PORT}'
        - '${IOTA_SOUTH_PORT}:${IOTA_SOUTH_PORT}'
    environment:
        - IOTA_CB_HOST=orion
        - IOTA_CB_PORT=1026
        - IOTA_NORTH_PORT=${IOTA_NORTH_PORT}
        - IOTA_REGISTRY_TYPE=mongodb
        - IOTA_LOG_LEVEL=DEBUG
        - IOTA_TIMESTAMP=true
        - IOTA_CB_NGSI_VERSION=ld
        - IOTA_AUTOCAST=true
        - IOTA_MONGO_HOST=mongo-db
        - IOTA_MONGO_PORT=27017
        - IOTA_MONGO_DB=iotagentjson
        - IOTA_HTTP_PORT=${IOTA_SOUTH_PORT}
        - IOTA_PROVIDER_URL=http://iot-agent:4041
        #- IOTA_DEFAULT_RESOURCE=/iot/json
        - IOTA_JSON_LD_CONTEXT=https://uri.etsi.org/ngsi-ld/v1/ngsi-ld-core-context.jsonld #The location of the @context file used to define the device data models
        - IOTA_FALLBACK_TENANT=openiot #The tenant to use if no explicit tenant has been received from communications
        - IOTA_MQTT_HOST=mosquitto
        - IOTA_MQTT_PORT=1883
        
# Database
  mongo-db:
    image: mongo:${MONGO_DB_VERSION}
    hostname: mongo-db
    container_name: db-mongo
    expose:
      - "${MONGO_DB_PORT}"
    ports:
      - "${MONGO_DB_PORT}:${MONGO_DB_PORT}" # localhost:27017
    networks:
      - default
    volumes:
      - mongo-db:/data
    healthcheck:
      test: [ "CMD", "mongo", "--quiet", "127.0.0.1/test", "--eval", "'quit(db.runCommand({ ping: 1 }).ok ? 0 : 2)'"]
      interval: 5s

    
networks:
  default:
    name: fiware-iotagent

volumes:
  mongo-db: ~